name: input test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Your name'
        required: true

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#literals
      - name: say hello
        run: echo 'Hi, I''m ${{ inputs.name }}.'
      - name: print age
        run: echo 'I''m ${{ inputs.age }} years old.'
